PAGE_HOME = 'home/'
PAGE_LOGIN = 'login/'
PAGE_LOGOUT = 'logout/'
PAGE_AFTER_LOGOUT = ''

RECORD_TYPE_ASSET_NAME = 'asset'
RECORD_TYPE_ASSET_ID = None

RECORD_TYPE_LIABILITY_NAME = 'liability'
RECORD_TYPE_LIABILITY_ID = None
